### PR TITLE
Add smoother loading for album art #6

### PR DESCRIPTION
**Pull request by Jwright707**
Added smooth loading for the album art. I used [this link](https://blog.hubspot.com/website/css-fade-in) as a reference for the fading in.

### CODE REVIEW

**Comment by luk-str** [comment]
@Jwright707 Thanks Joshua!

The animation looks good but it starts before the image is done loading - once the file from the internet archive server is loaded, it then jumps into place in the middle of the animation.

I think the animation should only start once the image is loaded and ready to be shown so that we get a smooth fade-in 🙃

**Comment by Jwright707** [comment]
Hi @luk-str, I added a fix to the fade-in effect. It's interesting because when looking at some of the image source URLs I've noticed that the loading on specific URLs takes a while to load. I don't know if it's my internet or just that specific website. Thank you for the feedback and looking forward to hearing back from you.

**Comment by luk-str** [comment]
Thanks! 🙌  Looks nice and smooth on my end but I'm on a fast connection and I'm worried it might not work as well on slower connections. Also the Internet Archive server's speed varies, it mostly works fine but sometimes it's quite slow and that's something we can't control.

Right now the animation is tied to time only. It starts the fade in no matter the state of the image.
It might be better to make it kick in only once the image is loaded. It can probably be done by setting up an event listener and adding a class with the animation to the Image object once it has downloaded the image 🤔 

Yeah, some of the image files are huge so they take a while to load 😞
If you like you can have a look at the file list that the Internet Archive API returns, maybe there's a smaller version of the album art that could be used (?) Just keep in mind that the available files vary from item to item so that not every type of file is present in every item ❗

**Comment by Jwright707** [comment]
Hi @luk-str , thank yo for the feedback, I added lazy loading to the image tag and it seems to have fixed the image loading issue. 😃

**Comment by luk-str** [comment]
As you can see [here](https://nextjs.org/docs/api-reference/next/image#loading) the next/image component that is used is actually loading lazy by default. Thus the change unfortunately has no effect.

**Comment by luk-str** [comment]
Just got it fixed, you can look at commit 365b2428c0df94bd7eee5d7267abd691c9a19e35 to see the implementation 🧰 

Thanks for your effort though, feel free to have a look at other issues and give them a try! 🙌

**Pull request closed without merging**
